variable "url" {
  type    = string
  default = "https://anywhere.altinity.cloud"
}

variable "image" {
  description = "Custom Docker image (defaults to altinity/cloud-connect:$version)."
  type        = string
  default     = "altinity/cloud-connect:0.20.0@sha256:1172a82a03f27567b517a2fdbc3079f91ee4ab2124c7d6ec95d0c0c6c34db78f"
}

variable "pem" {
  type        = string
  description = <<EOT
The contents of cloud-connect.pem generated by https://github.com/altinity/altinitycloud-connect login.

Omit if you want to keep the value out of Terraform state by loading certificate from AWS SSM Parameter
indicated by "pem_ssm_parameter_name" variable.
EOT
  default     = ""
}

variable "pem_ssm_parameter_name" {
  description = <<EOT
AWS SSM Parameter that contains cloud-connect.pem generated by https://github.com/altinity/altinitycloud-connect login.

Required if "pem" variable isn't set.
EOT
  type        = string
  default     = ""
}

variable "subnets" {
  description = <<EOT
A list of subnets (with access to the Internet) where to launch cloud-connect EC2 instance(s).

If "subnets" is empty and "use_default_subnets" is false (default), this module creates new VPC/subnets.
EOT
  type        = list(string)
  default     = []
}

variable "map_public_ip_on_launch" {
  type    = bool
  default = true
}

variable "use_default_subnets" {
  description = <<EOT
Use default subnets to launch cloud-connect EC2 instance(s).

If "subnets" is empty and "use_default_subnets" is false (default), this module creates new VPC/subnets.
EOT
  type        = bool
  default     = false
}

variable "instance_type" {
  description = "The EC2 instance type (e.g. t2.micro, t3.micro, t3.medium, t4g.micro, t4g.medium)."
  type        = string
  default     = "t3.micro"
}

variable "replicas" {
  description = "Number of altinity/cloud-connect replicas (EC2 instances)."
  type        = number
  default     = 1
  validation {
    condition     = var.replicas >= 1 && var.replicas <= 3
    error_message = "The number of replicas must be between 1 and 3."
  }
}

variable "allow_altinity_access" {
  description = "Allow Altinity access to the cloud-connect EC2 instance(s) (part of break-glass procedure)."
  type        = bool
  default     = true
}

variable "break_glass_principal" {
  type    = string
  default = ""
}

variable "tags" {
  description = "Set of tags to apply to all resources created by this module."
  type        = map(string)
  default     = {}
}

variable "ami_name" {
  description = "The name of the AMI to use for the EC2 instance."
  type        = string
  default     = ""
}

variable "container_registry" {
  description = "name of the container registry"
  type        = string
  default     = "value"
}